export const LOGIN = 'API:LOGIN';
export const REGISTER = 'API:REGISTER';
export const LOGOUT = 'API:LOGOUT';
export const LOGIN_ERROR = 'API:LOGIN_ERROR';
export const REGISTER_ERROR = 'API:REGISTER_ERROR';
export const LOGOUT_ERROR = 'API:LOGOUT_ERROR';
export const GOOGLE_LOGIN = 'API:GOOGLE_LOGIN';
export const GOOGLE_LOGIN_ERROR = 'API:GOOGLE_LOGIN_ERROR';

export const GET_PROJECTS = 'API:GET_PROJECTS';
export const GET_ONE_PROJECT = 'API:GET_ONE_PROJECT';
export const GET_PROJECT = 'API:GET_PROJECT';
export const ADD_PROJECT = 'API:ADD_PROJECT';
export const UPDATE_PROJECT = 'API:UPDATE_PROJECT';
export const DELETE_PROJECT = 'API:DELETE_PROJECT';
export const SEARCH_PROJECT = 'API:SEARCH_PROJECT';
export const GET_USER_PROJECTS = 'API:GET_USER_PROJECTS';

export const GET_MARKERS = 'GET_MARKERS';
export const ADD_MARKER = 'ADD_MARKER';
export const MOVE_MARKER = 'MOVE_MARKER';
export const ADD_COMMENT = 'ADD_COMMENT';
export const GET_MARKER_COMMENT = 'GET_MARKER_COMMENT';
export const RESIZE_MARKER = 'RESIZE_MARKER';
export const DELETE_MARKER = 'DELETE_MARKER';
export const RESOLVE_MARKER = 'RESOLVE_MARKER';

export const GET_TAGS = 'API:GET_TAGS';
export const GET_CATEGORIES = 'API:GET_CATEGORIES';

export const SHOW_REGISTER_WINDOW = 'SHOW_REGISTER_WINDOW';
export const SHOW_LOGIN_WINDOW = 'SHOW_LOGIN_WINDOW';
export const COMPLETE_REGISTRATION = 'COMPLETE_REGISTRATION';

export const GET_ALL_USERS = 'API:GET_ALL_USERS';
export const GET_ALL_USERS_ERROR = 'API:GET_ALL_USERS_ERROR';

export const UPLOAD_PROFILE_IMAGE = 'API:UPLOAD_PROFILE_IMAGE';
export const UPLOAD_PROJECT_IMAGES = 'API:UPLOAD_PROJECT_IMAGES';
export const UPLOAD_REVISION_IMAGE = 'API:UPLOAD_REVISION_IMAGE';

export const DOWNLOAD_PROJECT_IMAGE_URLS = 'API:DOWNLOAD_PROJECT_IMAGE_URLS';

export const USER_SETTINGS_UPDATE = 'USER_SETTINGS_UPDATE';

export const HYDRATE_USER = 'HYDRATE_USER';
