export const LOGIN = 'API:LOGIN';
export const REGISTER = 'API:REGISTER';
export const LOGOUT = 'API:LOGOUT';
export const LOGIN_ERROR = 'API:LOGIN_ERROR';
export const REGISTER_ERROR = 'API:REGISTER_ERROR';
export const LOGOUT_ERROR = 'API:LOGOUT_ERROR';

export const GET_PROJECTS = 'API:GET_PROJECTS';
export const ADD_PROJECT = 'API:ADD_PROJECT';
export const UPDATE_PROJECT = 'API:UPDATE_PROJECT';
export const DELETE_PROJECT = 'API:DELETE_PROJECT';

export const GET_TAGS = 'API:GET_TAGS';
export const GET_CATEGORIES = 'API:GET_CATEGORIES';

export const SHOW_REGISTER_WINDOW = 'SHOW_REGISTER_WINDOW';
export const SHOW_LOGIN_WINDOW = 'SHOW_LOGIN_WINDOW';
